[[librdkafka]]
arch = "aarch64"
git-tree-sha1 = "329970f3b11d8acceb7646c6dc04c331e33bc3cf"
os = "macos"

    [[librdkafka.download]]
    sha256 = "fabb2eeabd55d1c00aa0d0468957346d21d49f246e8aa5dc4a74d6ce434eb840"
    url = "https://github.com/JuliaBinaryWrappers/librdkafka_jll.jl/releases/download/librdkafka-v2.13.0+0/librdkafka.v2.13.0.aarch64-apple-darwin.tar.gz"
[[librdkafka]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "edc3d6da113cd95debc5ee30e2f82ab4eb922e0a"
libc = "glibc"
os = "linux"

    [[librdkafka.download]]
    sha256 = "519a11b498305506c4b7fbde156ee493c12dd2d825d30f6c9232b42873018171"
    url = "https://github.com/JuliaBinaryWrappers/librdkafka_jll.jl/releases/download/librdkafka-v2.13.0+0/librdkafka.v2.13.0.aarch64-linux-gnu-cxx11.tar.gz"
[[librdkafka]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dafddf2f81787db9b4d1f92724577d55c4ac93fe"
libc = "musl"
os = "linux"

    [[librdkafka.download]]
    sha256 = "c427311612f51270784b6a60d0d718c696d4cc2cf2b9abbbaac057f8a372a83f"
    url = "https://github.com/JuliaBinaryWrappers/librdkafka_jll.jl/releases/download/librdkafka-v2.13.0+0/librdkafka.v2.13.0.aarch64-linux-musl-cxx11.tar.gz"
[[librdkafka]]
arch = "aarch64"
git-tree-sha1 = "bcbc461a6131c6bf98f71a1d7d040c6835410b43"
os = "freebsd"

    [[librdkafka.download]]
    sha256 = "e15d92d4b8fa21595b50b9a13a38f6c4ac08f3efbc62dbcc0233a134e884a147"
    url = "https://github.com/JuliaBinaryWrappers/librdkafka_jll.jl/releases/download/librdkafka-v2.13.0+0/librdkafka.v2.13.0.aarch64-unknown-freebsd.tar.gz"
[[librdkafka]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "672681d3fdbb3e70f1e295572bc6db5c6d45173f"
libc = "glibc"
os = "linux"

    [[librdkafka.download]]
    sha256 = "d16f7355cd70365ab70ef6f5d6bc2ae033c799564b1a9501bfd3f5a488cd8370"
    url = "https://github.com/JuliaBinaryWrappers/librdkafka_jll.jl/releases/download/librdkafka-v2.13.0+0/librdkafka.v2.13.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[librdkafka]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4260daa4a6d7273d688503b9a4a5bfec8fba63cb"
libc = "musl"
os = "linux"

    [[librdkafka.download]]
    sha256 = "70f355ad1d265fca5396088ebff89a1e792d729b0e2b810f320991aa40f59626"
    url = "https://github.com/JuliaBinaryWrappers/librdkafka_jll.jl/releases/download/librdkafka-v2.13.0+0/librdkafka.v2.13.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[librdkafka]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aaf9001d8f647a9ed6ae0f04531de9558975c74c"
libc = "glibc"
os = "linux"

    [[librdkafka.download]]
    sha256 = "a3a199a4414fa731eda6f566ada969bd2486d087cf404e6a3dce83f00e50eca4"
    url = "https://github.com/JuliaBinaryWrappers/librdkafka_jll.jl/releases/download/librdkafka-v2.13.0+0/librdkafka.v2.13.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[librdkafka]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01d7302a081caa0c1d8509d751a8ddf5f613b9ee"
libc = "musl"
os = "linux"

    [[librdkafka.download]]
    sha256 = "16a7dad37a7c453b5bc9cb4bd7256ccf12002b2450c1e08c9f7b4a3a38f0c28a"
    url = "https://github.com/JuliaBinaryWrappers/librdkafka_jll.jl/releases/download/librdkafka-v2.13.0+0/librdkafka.v2.13.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[librdkafka]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2f2f3e7a9371b71c563a9f587a325f7dd82186d"
libc = "glibc"
os = "linux"

    [[librdkafka.download]]
    sha256 = "3a4b145636c457e127809f4aaa9df7eebb13cdf1510601654ff3187a417f2092"
    url = "https://github.com/JuliaBinaryWrappers/librdkafka_jll.jl/releases/download/librdkafka-v2.13.0+0/librdkafka.v2.13.0.i686-linux-gnu-cxx11.tar.gz"
[[librdkafka]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d7f5d20e3fa19e0c306014b2cdfa3f1014e1e1b"
libc = "musl"
os = "linux"

    [[librdkafka.download]]
    sha256 = "926d55cfe7a3ffa8e79695301c5061da8d8ad5bd4e9a5cea1d983f960a86de84"
    url = "https://github.com/JuliaBinaryWrappers/librdkafka_jll.jl/releases/download/librdkafka-v2.13.0+0/librdkafka.v2.13.0.i686-linux-musl-cxx11.tar.gz"
[[librdkafka]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b198668a931754bfb32e1323843d4984c0de24a5"
os = "windows"

    [[librdkafka.download]]
    sha256 = "d00c271e7d652b6379c970d0b9700fcab85372ffb736e61968cc40d312c750d2"
    url = "https://github.com/JuliaBinaryWrappers/librdkafka_jll.jl/releases/download/librdkafka-v2.13.0+0/librdkafka.v2.13.0.i686-w64-mingw32-cxx11.tar.gz"
[[librdkafka]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb1e87868e923431e09b71612a79f61fb6997f7d"
libc = "glibc"
os = "linux"

    [[librdkafka.download]]
    sha256 = "a80c4158b5b372562c4fe8b360b5cfb994e81139e6068286eee0a8ea225ac374"
    url = "https://github.com/JuliaBinaryWrappers/librdkafka_jll.jl/releases/download/librdkafka-v2.13.0+0/librdkafka.v2.13.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[librdkafka]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cab89d6db7d62a3bb86ebf432a17e06436f38e64"
libc = "glibc"
os = "linux"

    [[librdkafka.download]]
    sha256 = "882eb173a736c55266aed0baeae9c922e806f2f1ac382ecb92c4fa20fd63ade2"
    url = "https://github.com/JuliaBinaryWrappers/librdkafka_jll.jl/releases/download/librdkafka-v2.13.0+0/librdkafka.v2.13.0.riscv64-linux-gnu-cxx11.tar.gz"
[[librdkafka]]
arch = "x86_64"
git-tree-sha1 = "f429dfba29bade41f0743a31ccdb312fa68271ef"
os = "macos"

    [[librdkafka.download]]
    sha256 = "d4e209bf0029d2673338f3928e6b908d7121fcc5cf1017ff4b3b9618d129b3bb"
    url = "https://github.com/JuliaBinaryWrappers/librdkafka_jll.jl/releases/download/librdkafka-v2.13.0+0/librdkafka.v2.13.0.x86_64-apple-darwin.tar.gz"
[[librdkafka]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "20c85f6f39783704f22a544508936861ce6cd66a"
libc = "glibc"
os = "linux"

    [[librdkafka.download]]
    sha256 = "4fc416fe5bf1e545a34075c102b0fad3cc91dd140773172a0c1a85f3d26adc01"
    url = "https://github.com/JuliaBinaryWrappers/librdkafka_jll.jl/releases/download/librdkafka-v2.13.0+0/librdkafka.v2.13.0.x86_64-linux-gnu-cxx11.tar.gz"
[[librdkafka]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a8f5a7cb0b11daf174667fb67001ea1bdd97f51"
libc = "musl"
os = "linux"

    [[librdkafka.download]]
    sha256 = "f566f59bfc2ff9a47d11c5b0a6885b86b93640c46a339b6e241aa812e93d740a"
    url = "https://github.com/JuliaBinaryWrappers/librdkafka_jll.jl/releases/download/librdkafka-v2.13.0+0/librdkafka.v2.13.0.x86_64-linux-musl-cxx11.tar.gz"
[[librdkafka]]
arch = "x86_64"
git-tree-sha1 = "140fd6cef95e6657490e6df0973c4c1d3765f595"
os = "freebsd"

    [[librdkafka.download]]
    sha256 = "3a90d145da1775d31a91a42daf987c5243765b944ed9eecf60e8fb14119844ba"
    url = "https://github.com/JuliaBinaryWrappers/librdkafka_jll.jl/releases/download/librdkafka-v2.13.0+0/librdkafka.v2.13.0.x86_64-unknown-freebsd.tar.gz"
[[librdkafka]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "60c31761b61c4cb4108b791b8b2772e771349902"
os = "windows"

    [[librdkafka.download]]
    sha256 = "3712ca31f948c1c718733a9649b85ada92526fa54725adccfa56b66b2bcfec7a"
    url = "https://github.com/JuliaBinaryWrappers/librdkafka_jll.jl/releases/download/librdkafka-v2.13.0+0/librdkafka.v2.13.0.x86_64-w64-mingw32-cxx11.tar.gz"
